---
id: labguide
name: AEC Lab Guide

content:
  url: https://raw.githubusercontent.com/PraveenAnil/openshift-container-platform-1/master/docs

vars:
  USER_NAME: "(email)"
  USER_PASSWORD: "(email)"
  GIT_HOST: github
  DOCS_URL: docs.spektrasystems.com

modules:
  activate:
  - Lab 01: Introduction-to-Azure-Portal
  - Lab 02: Deploying-OpenShift-cluster-using-ARM-templates
  - Lab 03: Deploying-workload-on-Openshift
  - Lab 04: Integration-of-ACR- with-OpenShift
  - Lab 05: Additional-Labs
