---
id: labguide
name: AEC Lab Guide

content:
  url: https://raw.githubusercontent.com/PraveenAnil/openshift-container-platform-1/master/docs

vars:
  USER_NAME: "(email)"
  USER_PASSWORD: "(email)"
  GIT_HOST: github
  DOCS_URL: docs.spektrasystems.com

modules:
  activate:
  - creds
  - Lab01a
  - Lab02a
  - Lab03a
  - Lab04a
  - Lab05a
